### PR TITLE
dg: Fix MeshWarp and EdgeBlending for multi-node rendering.

### PR DESCRIPTION
**Pull request by voidcycles**
The initial implementation I submitted omitted support for multi-node rendering.

This fixes issues with handling the tile geometry and rendering the captured frame buffer to allow multi-node non-linear warping and edge blending with Equalizer.

Please look this over closely.  I attempted to integrate the RenderCorrection into the GpuResource management policy that appears to be handled inside GpuContext but immediately ran into issues with lifetime management lots of random crashes.  Whose responsibility is it to call dispose() on constructed GpuResources?  Any suggestions to get this working?

Thanks!

### CODE REVIEW

**Comment by voidcycles** [comment]
Added more commits that address resource initialization problems I was encountering.  Now, the RenderCorrection is only initialized and enabled after all other render passes have been initialized.

**Comment by febret** [comment]
Thank you! Sorry I have not been able to get to this yet. Things busy on this end. It's on my todo list tho, I promise :grin:

**Comment by voidcycles** [comment]
FYI: Note that with your upstream changes I had to modify the external modules 'cyclops' and 'core.examples' to pull in 'DrawContext.h" otherwise they fail to build.

**Comment by febret** [comment]
merged into master for v16.0. Thanks!

**Pull request merged**
